/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan.pkg12;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import pertemuan.pkg12.koneksi;
/**
 *
 * @author LAB F
 */


public class design extends javax.swing.JFrame {

 /**
     * Creates new form design
     */
    public design() {
        initComponents();
    load_tabel();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kodecatatan = new javax.swing.JLabel();
        formnim = new javax.swing.JTextField();
        tempatwisata = new javax.swing.JLabel();
        formnama = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnhps = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelinput = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        formalmt = new javax.swing.JTextField();
        ulas_ = new javax.swing.JLabel();
        ulasan_ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kodecatatan.setText("Kode Catatan");

        formnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnimActionPerformed(evt);
            }
        });

        tempatwisata.setText("Tempat Wisata");

        btntambah.setBackground(new java.awt.Color(153, 255, 255));
        btntambah.setForeground(new java.awt.Color(51, 0, 51));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhps.setBackground(new java.awt.Color(204, 204, 204));
        btnhps.setText("Edit");
        btnhps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhpsActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tabelinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Catatan", "Tempat Wisata", "Tanggal", "Ulasan"
            }
        ));
        tabelinput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelinputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelinputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelinput);

        jLabel1.setText("Tanggal");

        ulas_.setText("Ulasan");

        jLabel2.setText("\"Sistem Catatan Perjalanan Wisata\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntambah)
                    .addComponent(btnhps)
                    .addComponent(btnhapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodecatatan)
                            .addComponent(tempatwisata)
                            .addComponent(jLabel1)
                            .addComponent(ulas_))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formnim, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(formnama)
                            .addComponent(formalmt)
                            .addComponent(ulasan_)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel2)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodecatatan)
                    .addComponent(formnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempatwisata)
                    .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formalmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ulas_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ulasan_, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhps)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnimActionPerformed

   
    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
       // Tambahan: Cek duplikat
        java.sql.Connection conn = koneksi.configDB();
        java.sql.PreparedStatement cek = conn.prepareStatement("SELECT * FROM catatwisata WHERE kode_catatan = ?");
        cek.setString(1, formnim.getText());
        java.sql.ResultSet hasil = cek.executeQuery();
        if (hasil.next()) {
            JOptionPane.showMessageDialog(this, "Kode Catatan sudah digunakan! Klik Tambah lagi untuk buat kode baru.");
            // Buat kode baru
            return;
        }

        // Kode lama kamu tetap seperti ini (tidak diubah):
        String sql = "INSERT INTO catatwisata VALUES('" + formnim.getText() + "','" + formnama.getText() + "','" + formalmt.getText() + "','" + ulasan_.getText() + "')";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        load_tabel();
         // Tambahan: langsung generate kode baru setelah tambah
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_btntambahActionPerformed

    private void tabelinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinputMouseClicked
    int baris = tabelinput.rowAtPoint(evt.getPoint());
    String kode_catatan =tabelinput.getValueAt(baris,1).toString();formnim.setText(kode_catatan);
    String tempat_wisata =tabelinput.getValueAt(baris,2).toString();formnama.setText(tempat_wisata); 
    String tanggal =tabelinput.getValueAt(baris,3).toString();formalmt.setText(tanggal);
    String ulasan =tabelinput.getValueAt(baris,4).toString();ulasan_.setText(ulasan);
    
    }//GEN-LAST:event_tabelinputMouseClicked

    private void tabelinputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelinputAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelinputAncestorAdded

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            String sql ="delete from catatwisata where kode_catatan='"+formnim.getText()+"'";
            java.sql.Connection
            conn=koneksi.configDB();
            java.sql.PreparedStatement
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,
                "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage());
        }
        load_tabel();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnhpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhpsActionPerformed
        try {
            String sql ="UPDATE catatwisata SET kode_catatan ='"+formnim.getText()+"', tempat_wisata = '"+formnama.getText()+"', tanggal = '"+formalmt.getText()+"', ulasan = '"+ulasan_.getText()+"'WHERE kode_catatan = '"+formnim.getText()+"'";
            java.sql.Connection
            conn=koneksi.configDB();
            java.sql.PreparedStatement
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Perubahan Data Gagal"+e.getMessage());
        }
        load_tabel();

    }//GEN-LAST:event_btnhpsActionPerformed
    
     
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhps;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField formalmt;
    private javax.swing.JTextField formnama;
    private javax.swing.JTextField formnim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodecatatan;
    private javax.swing.JTable tabelinput;
    private javax.swing.JLabel tempatwisata;
    private javax.swing.JLabel ulas_;
    private javax.swing.JTextField ulasan_;
    // End of variables declaration//GEN-END:variables

private void load_tabel() {
 {
 DefaultTableModel model = new
 DefaultTableModel();
 model.addColumn("No");
 model.addColumn("Kode Catatan");
 model.addColumn("Tempat Wisata");
 model.addColumn("Tanggal");
 model.addColumn("Ulasan");

 //menampilkan data database kedalam tabel
 try {
 int no=1;
    String sql = "select * from catatwisata"; java.sql.Connection
conn=koneksi.configDB();
 java.sql.Statement
stm=conn.createStatement();
 java.sql.ResultSet
res=stm.executeQuery(sql);
 while(res.next()){
 model.addRow(new
Object[]{no++,res.getString(1),res.getString(2), res.getString(3), res.getString(4)});
 }
 tabelinput.setModel(model);

 } catch (SQLException e) {
 }
 }
 }
}
